name: Demo

on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print info
        run: echo "CI triggered"
      