name: demo-rw
on:
  push:
    branches:
      - main

jobs:
  job1:
    uses: aswin0318/demo-workflow/.github/workflows/ci-reusable.yml@main
    with:
      branch: ${{ github.ref_name }}
      actor: ${{ github.actor }}
      repo: ${{ github.repository }}

    
            
