name: demo-rw1
on:
  push:
    branches:
      - main

jobs:
  job1:
    uses: ./.github/workflows/ci_reusable.yml
    with:
      branch: ${{ github.ref_name }}
      actor: ${{ github.actor }}
      repo: ${{ github.repository }}
      commit_id: ${{ github.sha }}
      message: "Hello"

    
            
